apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: awesomeapps
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJ5b3VyLnByaXZhdGUucmVnaXN0cnkuZXhhbXBsZS5jb20iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJqYW5lZG9lIiwKICAgICAgInBhc3N3b3JkIjogInh4eHh4eHh4eHh4IiwKICAgICAgImVtYWlsIjogImpkb2VAZXhhbXBsZS5jb20iLAogICAgICAiYXV0aCI6ICJjM1IuLi56RTIiCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
