apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myservice-simple-ingress
spec:
  rules:
    - host: myservice.wkng.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ngnix-cluster-ip
                port:
                  number: 80
