apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  ENABLE_SWITCH_A: "false"
  my_ini_file.ini: |
    car.1.brand = Tesla
    car.1.autonomy = 550km
    car.2.brand = Mazda
    car.2.autonomy = 120km
