apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-hilo-deployment
  namespace: hilo-1
spec:
  selector:
    matchLabels:
      app: hello-hilo-1
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-hilo-1
    spec:
      containers:
      - name: hello-hilo-1
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: MESSAGE
          value: "Hello Hilo Namespace hilo-1"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

---

apiVersion: v1
kind: Service
metadata:
  name: hello-hilo
spec:
  type: ClusterIP
  selector:
    app: hello-hilo-1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080