apiVersion: v1
kind: Service
metadata:
  name: ngnix-cluster-ip
spec:
  type: ClusterIP # <- Within the cluster network overlay
  selector:
    app: nginx-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
